[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[build.environment]
  NPM_VERSION = "6.4.1"
[[plugins]]
  package = "netlify-plugin-lighthouse"

  [plugins.inputs]
  url = "jonathan-harrell.netlify.com"
